# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Set environment for branch
      run: |
        if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "DOCKER_TAG=candyland-roller:1.0.0" >> "$GITHUB_ENV"
        else
            echo "DOCKER_TAG=candyland-roller:1.0.0-beta" >> "$GITHUB_ENV"
        fi
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: yarn.lock
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install --frozen-lockfile
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build
    - name: Test production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: test --coverage
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./coverage/cobertura-coverage.xml
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_TAG }}
